# Generated by Django 4.0 on 2021-12-11 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('btest', '0003_client_order_alter_bb_options_remove_bb_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cellarPosition', models.TextField(blank=True, null=True, verbose_name='Местоположение в погребе')),
                ('productionDate', models.DateTimeField(db_index=True, null=True, verbose_name='Дата изготовления')),
                ('vol', models.FloatField(blank=True, null=True, verbose_name='Объем')),
                ('isEmpty', models.BooleanField(verbose_name='Пустая')),
                ('dateOfFilling', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата заполнения')),
            ],
            options={
                'verbose_name': 'Бочка',
                'verbose_name_plural': 'Бочки',
                'ordering': ['dateOfFilling'],
            },
        ),
        migrations.CreateModel(
            name='wineKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('type', models.CharField(max_length=20, verbose_name='Тип')),
                ('color', models.CharField(max_length=20, verbose_name='Цвет')),
                ('AgeYears', models.FloatField(blank=True, null=True, verbose_name='Время выдержки бочки в годах')),
                ('AgeMonths', models.FloatField(blank=True, null=True, verbose_name='Время выдержки в бутылках в месяцах')),
            ],
            options={
                'verbose_name': 'Сорт вина',
                'verbose_name_plural': 'Сорта вин',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.RemoveField(
            model_name='order',
            name='good',
        ),
        migrations.AlterModelOptions(
            name='bb',
            options={'ordering': ['-date'], 'verbose_name': 'Сорт винограда', 'verbose_name_plural': 'Сорта винограда'},
        ),
        migrations.RemoveField(
            model_name='bb',
            name='article',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='basePrice',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='content',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='currentPrice',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bb',
            name='minCapacity',
        ),
        migrations.AddField(
            model_name='bb',
            name='date',
            field=models.DateTimeField(db_index=True, null=True, verbose_name='Время сбора'),
        ),
        migrations.AddField(
            model_name='bb',
            name='placeOfBirth',
            field=models.CharField(max_length=50, null=True, verbose_name='Место произрастания'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='winekind',
            name='grapeKind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='btest.bb', verbose_name='Сорт винограда'),
        ),
        migrations.AddField(
            model_name='barrel',
            name='wineKind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='btest.winekind', verbose_name='Сорт вина'),
        ),
    ]
